"""create payment tables

Revision ID: 670452c9e6fe
Revises: fbb4eda1923b
Create Date: 2026-08-31 11:35:57.971231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670452c9e6fe'
down_revision: Union[str, Sequence[str], None] = 'fbb4eda1923b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), server_default='', nullable=False),
    sa.Column('discount_type', sa.Enum('Fixed', 'PERCENT', name='discount_type', native_enum=False, length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('claimed_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_is_active'), 'coupons', ['is_active'], unique=False)
    op.create_table('user_coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'USED', 'EXPIRED', name='user_coupons_status', native_enum=False, length=20), server_default='AVAILABLE', nullable=False),
    sa.Column('claimed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'coupon_id', name='uq_user_coupons_user_coupon')
    )
    op.create_index(op.f('ix_user_coupons_coupon_id'), 'user_coupons', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_user_coupons_user_id'), 'user_coupons', ['user_id'], unique=False)
    op.create_index('ix_user_coupons_user_status', 'user_coupons', ['user_id', 'status'], unique=False)
    op.create_table('order_status_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING_PAYMENT', 'PAID', 'CANCELED', 'SHIPPED', 'COMPLETED', name='order_log_from_status', native_enum=False, length=30), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING_PAYMENT', 'PAID', 'CANCELED', 'SHIPPED', 'COMPLETED', name='order_log_to_status', native_enum=False, length=30), nullable=True),
    sa.Column('operator_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=255), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_logs_order_id'), 'order_status_logs', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_number', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), server_default='mockpay', nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'Succeeded', 'FAILED', 'CLOSED', name='payment_status', native_enum=False, length=20), server_default='PENDING', nullable=False),
    sa.Column('client_request_id', sa.String(length=64), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_transaction_id'),
    sa.UniqueConstraint('user_id', 'client_request_id', name='uq_user_payments_user_request')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_payment_number'), 'payments', ['payment_number'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('payment_callbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_callbacks_event_id'), 'payment_callbacks', ['event_id'], unique=True)
    op.create_index(op.f('ix_payment_callbacks_payment_id'), 'payment_callbacks', ['payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_callbacks_payment_id'), table_name='payment_callbacks')
    op.drop_index(op.f('ix_payment_callbacks_event_id'), table_name='payment_callbacks')
    op.drop_table('payment_callbacks')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_status_logs_order_id'), table_name='order_status_logs')
    op.drop_table('order_status_logs')
    op.drop_index('ix_user_coupons_user_status', table_name='user_coupons')
    op.drop_index(op.f('ix_user_coupons_user_id'), table_name='user_coupons')
    op.drop_index(op.f('ix_user_coupons_coupon_id'), table_name='user_coupons')
    op.drop_table('user_coupons')
    op.drop_index(op.f('ix_coupons_is_active'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
