"""add is_active to product skus

Revision ID: 8e1640312af1
Revises: e3ae8c5a401a
Create Date: 2026-08-17 10:09:33.608338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1640312af1'
down_revision: Union[str, Sequence[str], None] = 'e3ae8c5a401a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_skus', 'is_active')
    # ### end Alembic commands ###
