"""create payment tables

Revision ID: f42438355c6b
Revises: 670452c9e6fe
Create Date: 2026-08-31 16:26:17.616929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42438355c6b'
down_revision: Union[str, Sequence[str], None] = '670452c9e6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 先以可空列加入，否则 MySQL 会尝试用零日期填充已有订单，
    # 并在严格模式下报 1292 Incorrect datetime value。
    op.add_column(
        'orders',
        sa.Column('payment_expires_at', sa.DateTime(), nullable=True),
    )
    op.execute(
        sa.text(
            "UPDATE orders "
            "SET payment_expires_at = DATE_ADD(created_at, INTERVAL 30 MINUTE) "
            "WHERE payment_expires_at IS NULL"
        )
    )
    op.alter_column(
        'orders',
        'payment_expires_at',
        existing_type=sa.DateTime(),
        nullable=False,
    )
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'payment_expires_at')
    # ### end Alembic commands ###
